### ISSUE TITLE
Invalid move by bot

### ISSUE THREAD

**Issue by matteodelabre** [LinusCDE/chessmarkable#1]
I just played a game in easy mode and the program crashed with the following log:

```
thread 'main' panicked at 'Invalid move by bot: Move not found as possibility', src/scene/game_scene.rs:572:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Bot thread is terminating
Bot thread should terminate
```

I guess that the bot is trying to make an invalid move, or that the code which detects whether a move is valid has a bug. Unfortunately I did not keep track of all the moves. Here is a screenshot of the state in which it crashed (black plays).

![screendump](https://user-images.githubusercontent.com/1370040/95024942-6c762b00-0686-11eb-88b0-8ae72c8dc912.png)

**Comment by LinusCDE** [comment]
Thanks for the report. I'm a real noob in chess to be honest. So it's really nice to have some testing regarding this.

I have now removed most limitations on what a bot can do. The user usually can't to moves that result in him getting checkmated or other stupid stuff. My guess is that your bot tried to do that. While not illegal it is stupid, but I trust the bot to do valid moves (as long as it doesn't screw up the entire board state).

The release will be 0.3.2
