### ISSUE TITLE
Save game as file

### ISSUE THREAD

**Issue by Sematre** [LinusCDE/chessmarkable#10]
Great chess app!

I would love to be able to save my games as a file.
I saw that is already possible to output the FEN to the console.
But I'm using my remarkable primarily via the GUI and don't have shell access all the time.

I think it would be cool to have a 4th button in the top right corner that's called `Save Game`.
This button will create a new file at let's say `~/Games/Chess/2021-05-10_13-20.fen` (or something like that).
After the file is created a message should appear right at the bottom of the screen (same position where the engine error messages appear).

In the main menu you would be able to load a game either against the computer or a real player.

**Comment by Sematre** [comment]
You're right. I haven't thought about the need of a scrollable list.

I like the idea of having slots. That should work for the time being.

**Comment by LinusCDE** [comment]
Cool. I'll look to do this next week.

**Comment by LinusCDE** [comment]
Got to do the feature today.

I have though a lot about how to make the feature as intuitive as possible while also not changing to many things in the UI.

After selecting a game mode in the main menu, a user has now to choose to either continue on a slot or start over on it. The slot will be remembered and the game saved to it when quitting (renamed the "Main Menu" button to "Save & Quit").

<img src="https://user-images.githubusercontent.com/22298664/118847766-63ad2f00-b8ce-11eb-8a13-ee782a54c696.jpg" width="45%"> &nbsp; <img src="https://user-images.githubusercontent.com/22298664/118847960-96efbe00-b8ce-11eb-8953-46470b61796d.jpg" width="45%">

When there is no savestate for a slot, the "Continue on" button will act like the "Start over on" button. This is a technical difficulty I didn't want to tackle today. Maybe I'll remove this limitation once I implement a proper button.

The savestates are saved to `/home/root/.config/chessmarkable/savestates.yml` by default.

![screenshot3688](https://user-images.githubusercontent.com/22298664/118848199-d0c0c480-b8ce-11eb-8d16-539d3c39fa8e.png)

How do you find it. If it's good, I can release a new version with it.

Here is a binary with the newest changes. Just tranfer it onto the device and run it with `./chessmarkable` (on rM2: `rm2fb-client ./chessmarkable`).

**Comment by Sematre** [comment]
I just tried it on my reMarkable 2 and it works pretty good. 

Thanks for all the hard work and your contributions to the open source community :heart:
