### ISSUE TITLE
Application crashes on checkmate

### ISSUE THREAD

**Issue by edupont** [LinusCDE/chessmarkable#2]
I am seeing this in the console after playing a move checkmating the opponent king:
`
Bot moved
Bot is working...
Invalid non-moving move found. Doing null move instead.
thread 'main' panicked at 'assertion failed: self.checkers().is_empty()', /home/linus/.cargo/registry/src/github.com-1ecc6299db9ec823/pleco-0.5.0/src/board/mod.rs:891:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

I don't know if this is due to pleco itself, or if you are sending wrong data to the engine.

**Comment by LinusCDE** [comment]
I had some struggle with that already. The things is that the bot tends to make non-moving moves (just moves from src to dest) when the king is cornered. As far as I understand it, this is not legal at all. Some check (`gives_check(...)` or similar) does a assert against that which is why I replaced it with a null move. But this is also a quite hacky solution. I need to look up better ways on that.

Did the "Checkmate!" appear before the crash?

**Comment by edupont** [comment]
I have just seen that the issue #1 is related to this. The position in the picture is a checkmate for white.

No, there was no checkmate message.

In the case of checkmate (and of stalemate), the player has no legal move. I don't know what the engine attempts to do in this case, but from your comment in issue #1, it sounds like the engine attempts an illegal move instead. If this is the case, I would suggest you handle it this way:

- Don't play the illegal move, because it is just the engine assuming that the game is over
- If the engine is in a check position (and has no legal moves), it is a checkmate
- If the engine is *not* in a check position (and has no legal moves), it is a stalemate (draw)

**Comment by LinusCDE** [comment]
Good idea. I'm currently having lectures. I could reproduce the bug on checkmating the bot as well. I'll try to fix that in the evening (in about 6 hours). I'll also probably add the possibility to import/export the board as [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) to speed up testing your suggested fixed which sound promising.

**Comment by LinusCDE** [comment]
I think that I have sorted it out now. It now recognized a stalemate and check even before the bot tries to pull as "null move".

Here is a FEN that can easily result in a stalemate: `8/8/2Q5/4k3/1R6/8/6K1/8 w - - 0 46` (start with this state by setting `-i` to it).  
This one can be used to checkmate the black: `1R7/8/2Q5/4k3/1R6/8/6K1/8 w - - 0 46` (just added another rook to the mix).

Seems to work fine now. Let me know if you still manage to crash it.
